const trades = [
  { symbol: 'HDFCBANK', buyer: 'FII buy', setup: '9:15 entry', entry: 1945.2, current: 1987.6, sl: 1906.3, target: 2061.9, pnl: 3270, r: 1.09, status: 'Open', date: 'Sep 09' },
  { symbol: 'TATAMOTORS', buyer: 'DII buy', setup: 'PDH breakout', entry: 721.4, current: 748.9, sl: 706.9, target: 764.9, pnl: 3810, r: 1.91, status: 'Open', date: 'Sep 08' },
  { symbol: 'INFY', buyer: 'MF buy', setup: '9:15 entry', entry: 1542.8, current: 1528.4, sl: 1512.0, target: 1635.2, pnl: -920, r: -0.47, status: 'Open', date: 'Sep 08' },
  { symbol: 'ICICIBANK', buyer: 'FII buy', setup: '9:15 entry', entry: 1331.3, current: 0, sl: 1304.7, target: 1411.1, pnl: 6840, r: 2.57, status: 'Closed', result: 'Win', date: 'Sep 04' },
  { symbol: 'SUNPHARMA', buyer: 'DII buy', setup: 'PDH breakout', entry: 1738.5, current: 0, sl: 1703.7, target: 1842.9, pnl: -2500, r: -1, status: 'Closed', result: 'Loss', date: 'Sep 01' },
  { symbol: 'SBIN', buyer: 'MF buy', setup: '9:15 entry', entry: 814.2, current: 0, sl: 797.9, target: 863.1, pnl: 4110, r: 2.52, status: 'Closed', result: 'Win', date: 'Aug 29' },
  { symbol: 'LT', buyer: 'FII buy', setup: '9:15 entry', entry: 3640.7, current: 0, sl: 3567.9, target: 3859.1, pnl: 2620, r: 1.2, status: 'Closed', result: 'Win', date: 'Aug 25' },
  { symbol: 'BAJFINANCE', buyer: 'DII buy', setup: 'PDH breakout', entry: 912.8, current: 0, sl: 894.5, target: 967.7, pnl: -2380, r: -1, status: 'Closed', result: 'Loss', date: 'Aug 21' }
];
const money = n => `${n < 0 ? '−' : ''}₹${Math.abs(n).toLocaleString('en-IN')}`;
const price = n => `₹${n.toLocaleString('en-IN', {maximumFractionDigits: 2})}`;
const positionsBody = document.querySelector('#positions-body');
const journalBody = document.querySelector('#journal-body');
function renderPositions() { positionsBody.innerHTML = trades.filter(t => t.status === 'Open').map(t => { const change = ((t.current / t.entry - 1) * 100); return `<tr><td><div class="symbol"><span class="symbol-icon ${t.symbol === 'HDFCBANK' ? 'blue' : t.symbol === 'INFY' ? 'purple' : 'orange'}">${t.symbol[0]}</span><div><strong>${t.symbol}</strong><small>${t.setup}</small></div></div></td><td>${price(t.entry)}</td><td>${price(t.current)} <em class="${change >= 0 ? 'positive' : 'negative'}">${change > 0 ? '+' : ''}${change.toFixed(1)}%</em></td><td>${price(t.sl)}</td><td>${price(t.target)}</td><td class="${t.r >= 0 ? 'positive' : 'negative'}">${t.r > 0 ? '+' : ''}${t.r}R</td><td class="${t.pnl >= 0 ? 'positive' : 'negative'}">${money(t.pnl)}</td></tr>`; }).join(''); }
function renderJournal() { const search = document.querySelector('#trade-search').value.toLowerCase(); const status = document.querySelector('#trade-status').value; const result = document.querySelector('#trade-result').value; const shown = trades.filter(t => (status === 'all' || t.status === status) && (result === 'all' || t.result === result) && `${t.symbol} ${t.buyer} ${t.setup}`.toLowerCase().includes(search)); journalBody.innerHTML = shown.map(t => `<tr><td><div class="symbol"><span class="symbol-icon ${t.symbol === 'HDFCBANK' ? 'blue' : 'purple'}">${t.symbol[0]}</span><div><strong>${t.symbol}</strong><small>${t.setup} · ${t.buyer}</small></div></div></td><td>${t.date}</td><td>${price(t.entry)}</td><td><strong>${price(t.sl)}</strong><small>${price(t.target)}</small></td><td><span class="status-pill ${t.status.toLowerCase()}">${t.status}</span></td><td class="${t.pnl >= 0 ? 'positive' : 'negative'}">${money(t.pnl)}</td><td class="${t.r >= 0 ? 'positive' : 'negative'}">${t.r > 0 ? '+' : ''}${t.r}R</td></tr>`).join('') || `<tr><td colspan="7" class="empty">No trades match those filters.</td></tr>`; document.querySelector('#journal-count').textContent = trades.length; }
renderPositions(); renderJournal();
document.querySelectorAll('.nav-item, [data-go]').forEach(button => button.addEventListener('click', () => { const view = button.dataset.view || button.dataset.go; if (!view) return; document.querySelectorAll('.view').forEach(v => v.classList.toggle('active-view', v.id === view)); document.querySelectorAll('.nav-item').forEach(n => n.classList.toggle('active', n.dataset.view === view)); document.querySelector('#page-title').textContent = {dashboard:'Good morning, Arun ✦',journal:'Trade journal',backtest:'Strategy backtests',rules:'Strategy rulebook'}[view]; window.scrollTo({top:0, behavior:'smooth'}); }));
['trade-search','trade-status','trade-result'].forEach(id => document.querySelector(`#${id}`).addEventListener('input', renderJournal));
const dialog = document.querySelector('#trade-dialog');
document.querySelectorAll('#new-trade,#journal-new-trade').forEach(b => b.addEventListener('click', () => dialog.showModal()));
const inputs = ['form-entry','form-sl','form-rr'].map(id => document.querySelector(`#${id}`));
function updateTarget() { const [entry, sl, rr] = inputs.map(i => Number(i.value)); document.querySelector('#target-preview').textContent = entry && sl ? price(entry + (entry - sl) * rr) : '—'; }
inputs.forEach(i => i.addEventListener('input', updateTarget));
document.querySelector('#save-trade').addEventListener('click', event => { const symbol = document.querySelector('#form-symbol').value.trim().toUpperCase(), [entry, sl, rr] = inputs.map(i => Number(i.value)); if (!symbol || !entry || !sl) return; const target = entry + (entry - sl) * rr; trades.unshift({symbol, buyer:'Manual paper trade', setup:'Manual entry', entry, current:entry, sl, target, pnl:0, r:0, status:'Open', date:'Today'}); renderPositions(); renderJournal(); dialog.close(); event.preventDefault(); });

